name: Daily Repository Update

on:
  schedule:
    - cron: "* 4 * * *"  # Runs daily at 02:30 UTC (Set to a fixed time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Prevents auth issues

      - name: Set Up Git Config (harshkumar.prasad@straive.com)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "harshkumar.prasad@straive.com"

      - name: Create or Update a File
        run: |
          echo "Daily update: $(date)" > daily_update.txt
          git add daily_update.txt
          git commit -m "Automated daily update - $(date)"

      - name: Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git pull --rebase https://x-access-token:$GH_TOKEN@github.com/Harsh2KumarPrasad/Github-Actions.git main
          git push https://x-access-token:$GH_TOKEN@github.com/Harsh2KumarPrasad/Github-Actions.git main

      - name: Confirm Commit
        run: git log -1
